spring:
  application:
    name: notification-service

  environment:
    - SPRING_PROFILES_ACTIVE=docker

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        max-attempts: 10       # retry up to 10 times
        initial-interval: 5000 # start retrying after 5 seconds
        multiplier: 2.0        # exponential backoff
        max-interval: 30000    # max interval between retries in ms


  data:
    mongodb:
      uri: mongodb://mongo:27017/notifications
