spring:
  application:
    name: notification-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: mongodb://mongo:27017/notifications
