version: '3.8'

# Define a common template for services to avoid repetition
x-base-service: &base-service
  restart: unless-stopped
  networks:
    - microservices-network

services:
  api-gateway:
    <<: *base-service
    # build context corrected to match local folder name
    build: ./api_gateway
    container_name: api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - user-service
      - song-service
      - mongo

  user-service:
    <<: *base-service
    # build context corrected to match local folder name
    build: ./user_service
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  song-service:
    <<: *base-service
    # build context corrected to match local folder name
    build: ./song-management-service
    container_name: song-service
    ports:
      - "8082:8082"
    volumes:
      - song-data:/app/music
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/music
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo

  notification-service:
    <<: *base-service
    build: ./notification_service
    container_name: notification-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - microservices-network
    depends_on:
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # main AMQP port
      - "15672:15672" # management UI
    networks:
      - microservices-network
  mongo:
    <<: *base-service
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

# Default driver is 'bridge', so it can be omitted
networks:
  microservices-network:

# Default driver is 'local', so it can be omitted
volumes:
  song-data:
  mongo_data: